# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Fullerton
email: andrew.fullerton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Design and Front-End Development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.andewfullerton.co" # the base hostname & protocol for your site
twitter_username: andrewfullerton
github_username:  AndrewKF

# Build settings
markdown: kramdown

exclude:
 - Capfile
 - config